import test from 'node:test';import assert from 'node:assert/strict';
import {newSnake,turnSnake,stepSnake,moveToken,boardCell,rollDie,transitions} from '../src/arcade-rules';
test('Snake rejects reverse and multiple turns between simulation ticks',()=>{const s=newSnake();const reversed=turnSnake(s,'left');assert.equal(reversed.direction,'right');const turn=turnSnake(s,'up');assert.equal(turnSnake(turn,'left').direction,'up');assert.equal(stepSnake(turn,()=>0).body[0].y,s.body[0].y-1);});
test('Snake grows, scores, avoids food overlap and ends on walls or itself',()=>{let s=newSnake();s={...s,food:{x:s.body[0].x+1,y:s.body[0].y}};const grown=stepSnake(s,()=>0);assert.equal(grown.score,1);assert.equal(grown.body.length,s.body.length+1);assert.ok(!grown.body.some(p=>p.x===grown.food?.x&&p.y===grown.food?.y));assert.equal(stepSnake({...s,body:[{x:15,y:0}],direction:'right'},()=>0).status,'over');const loop={...s,body:[{x:3,y:3},{x:4,y:3},{x:4,y:4},{x:3,y:4},{x:2,y:4}],direction:'down' as const};assert.equal(stepSnake(loop,()=>0).status,'over');});
test('Snakes and ladders applies transitions and requires an exact finish',()=>{assert.deepEqual(moveToken(0,1),{landed:1,position:38,transition:'ladder',won:false});assert.equal(moveToken(15,1).position,6);assert.equal(moveToken(99,2).position,99);assert.equal(moveToken(94,6).won,true);assert.equal(moveToken(98,1).position,99);assert.ok(Object.keys(transitions).length>10);});
test('the board snakes continuously from bottom left to square 100 and dice are bounded',()=>{assert.deepEqual(boardCell(1),{row:9,col:0});assert.deepEqual(boardCell(10),{row:9,col:9});assert.deepEqual(boardCell(11),{row:8,col:9});assert.deepEqual(boardCell(100),{row:0,col:0});assert.equal(rollDie(()=>0),1);assert.equal(rollDie(()=>.999999),6);assert.throws(()=>moveToken(0,7));});
test('overshooting never retriggers the transition under a stationary token',()=>{assert.deepEqual(moveToken(98,6),{landed:98,position:98,transition:null,won:false});});
test('moving into the vacating tail is allowed and a full board completes Snake',()=>{const s=newSnake();const tailTurn={...s,body:[{x:2,y:2},{x:3,y:2},{x:3,y:3},{x:2,y:3}],direction:'down' as const};assert.equal(stepSnake(tailTurn).status,'playing');const cells=[];for(let y=0;y<16;y++)for(let x=0;x<16;x++)if(x!==0||y!==0)cells.push({x,y});const full={...s,body:[{x:1,y:0},...cells.filter(p=>p.x!==1||p.y!==0)],direction:'left' as const,food:{x:0,y:0}};assert.equal(stepSnake(full).status,'won');});
test('same-direction Snake key repeats preserve the next turn allowance',()=>{const snake=newSnake();const repeated=turnSnake(turnSnake(snake,'right'),'right');assert.equal(repeated.turned,false);const turned=turnSnake(repeated,'up');assert.equal(turned.direction,'up');assert.equal(turned.turned,true);assert.equal(turnSnake(turned,'left').direction,'up');});
