import test from 'node:test';
import assert from 'node:assert/strict';
import {AudioMix,defaultAudioPreferences,parseAudioPreferences} from '../src/audio-mix';
const frame=(speed=0,throttle=0,extra={})=>({dt:1/60,speed,throttle,worldActive:true,paused:false,visitorPhase:'waiting' as const,visitorPan:0,...extra});
test('first drive starts the engine once, repeated frames do not retrigger, and driving increases motor pitch',()=>{const m=new AudioMix();m.unlock();const first=m.step(frame(.1,1));assert.deepEqual(first.events,['engine-start']);let fast=first;for(let i=0;i<120;i++){fast=m.step(frame(5,1));assert.equal(fast.events.length,0);}assert.ok(fast.driveGain>first.driveGain);assert.ok(fast.driveRate>first.driveRate);for(let i=0;i<100;i++)m.step(frame());const restart=m.step(frame(.1,1));assert.deepEqual(restart.events,['engine-rev']);});
test('explicit mute survives new movement and all loop and one-shot channels remain silent',()=>{const m=new AudioMix({...defaultAudioPreferences,muted:true,music:true});m.unlock();for(let i=0;i<120;i++){const out=m.step(frame(4,1,{visitorPhase:'arriving'}));assert.equal(out.master,0);assert.equal(out.events.length,0);}assert.equal(m.preferences.muted,true);});
test('music can be disabled independently while drive and ambience remain audible',()=>{const m=new AudioMix({...defaultAudioPreferences,music:true});m.unlock();for(let i=0;i<100;i++)m.step(frame(4,1));m.setPreferences({music:false});const out=m.step(frame(4,1));assert.equal(out.musicOn,false);assert.ok(out.driveGain>0);assert.ok(out.ambientGain>0);});
test('pan follows a visitor and pause prevents engine or visitor events',()=>{const m=new AudioMix();m.unlock();const arrive=m.step(frame(0,0,{visitorPhase:'arriving',visitorPan:-.8}));assert.ok(arrive.events.includes('ufo-approach'));assert.equal(arrive.visitorPan,-.8);for(let i=0;i<100;i++){const out=m.step(frame(4,1,{paused:true,visitorPhase:'arriving'}));assert.deepEqual(out.events,[]);}const hovering=m.step(frame(0,0,{visitorPhase:'admiring',visitorPan:.4}));assert.ok(hovering.hoverGain>0);assert.equal(hovering.visitorPan,.4);});
test('saved audio preferences reject corrupt values and retain a deliberate mute',()=>{assert.deepEqual(parseAudioPreferences('{broken'),defaultAudioPreferences);const value=parseAudioPreferences(JSON.stringify({muted:true,music:true,effectsVolume:50,musicVolume:-3,ambienceVolume:'loud'}));assert.equal(value.muted,true);assert.equal(value.music,true);assert.equal(value.effectsVolume,1);assert.equal(value.musicVolume,0);assert.equal(value.ambienceVolume,defaultAudioPreferences.ambienceVolume);});
