import {useEffect,useRef,useState,type ReactNode} from 'react';
import {AnimatePresence,motion,MotionConfig,useReducedMotion} from 'motion/react';
import {Asterisk,ArrowUp,ArrowDown,ArrowLeft,ArrowRight,ArrowUpRight,Volume2,VolumeX,Music2,RotateCcw,MousePointer2,Keyboard,Orbit,Settings2,Satellite,Sparkles,Globe2,Move,Radio,Accessibility} from 'lucide-react';
import {Slider} from './components/ui/slider';import {Card} from './components/ui/card';import {Badge} from './components/ui/badge';import {Button} from './components/ui/button';import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogHeader} from './components/ui/dialog';import {Tooltip,TooltipTrigger,TooltipContent,TooltipProvider}from './components/ui/tooltip';
import {BlurFade}from './components/magicui/blur-fade';import {TextGenerateEffect}from './components/aceternity/text-generate-effect';import {WorkshopAudio,readAudioPreferences,type AudioSnapshot}from './audio';import type{LunarGame,LunarState}from './lunar-game';import {identity,safeLink,type AreaId}from './content';
const initial:LunarState={ready:false,started:false,nearby:null,visitor:null,visitorX:50,visitorY:25,distance:0,phase:'waiting',fps:0,error:null};
type Panel=AreaId|'controls'|null;
function Tool({label,children}:{label:string;children:ReactNode}){return <Tooltip><TooltipTrigger asChild>{children}</TooltipTrigger><TooltipContent>{label}</TooltipContent></Tooltip>;}
export function LunarApp(){
 const host=useRef<HTMLDivElement>(null),game=useRef<LunarGame|null>(null),audio=useRef<WorkshopAudio|null>(null),returnFocus=useRef<HTMLElement|null>(null),dialogHeading=useRef<HTMLHeadingElement|null>(null);
 const[state,setState]=useState(initial),[panel,setPanel]=useState<Panel>(null),[audioState,setAudioState]=useState<AudioSnapshot>(()=>({preferences:readAudioPreferences(),unlocked:false,loading:false,errors:[]})),[visitors,setVisitors]=useState(()=>!matchMedia('(prefers-reduced-motion: reduce)').matches),[flat,setFlat]=useState(new URLSearchParams(location.search).has('flat'));
 const sound=!audioState.preferences.muted;const music=audioState.preferences.music;const reduced=useReducedMotion();const paused=useRef(false);
 const open=(area:Panel)=>{returnFocus.current=document.activeElement as HTMLElement;setPanel(area);};
 useEffect(()=>{const instance=new WorkshopAudio(setAudioState);audio.current=instance;return()=>{instance.dispose();audio.current=null;};},[]);
 useEffect(()=>{let cancelled=false;if(flat)return;void import('./lunar-game').then(async({LunarGame})=>{if(cancelled||!host.current)return;const instance=new LunarGame(host.current,audio.current!,s=>{if(!cancelled)setState(s);},area=>open(area));game.current=instance;await instance.init();instance.setVisitors(visitors);instance.setPaused(paused.current);});return()=>{cancelled=true;game.current?.dispose();game.current=null;};},[flat]);
 useEffect(()=>{paused.current=!!panel||flat;game.current?.setPaused(paused.current);},[panel,flat]);
 const simple=flat||!!state.error;
 const reset=()=>{game.current?.home();document.querySelector<HTMLCanvasElement>('canvas')?.focus();};
 const visit=()=>{game.current?.hailVisitor();setPanel(null);};
 const toggleVisitors=()=>{setVisitors(v=>{game.current?.setVisitors(!v);return!v;});};
 const direction=(x:number,z:number)=>(e:React.PointerEvent<HTMLButtonElement>)=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);game.current?.setTouch(x,z);};
 const stop=()=>game.current?.setTouch(0,0);
 return <MotionConfig reducedMotion="user"><TooltipProvider delayDuration={250}>
  <a className="skip-link" href="#portfolio-navigation">Skip to portfolio navigation</a>
  <main className={`lunar-app ${state.started?'is-exploring':''} ${simple?'is-simple':''}`}>
   {!flat&&<div ref={host} id="lunar-world" data-testid="lunar-world" aria-label="Interactive spherical lunar world"/>}
   <header className="lunar-header">
    <Button variant="ghost" className="brand-button" onClick={()=>simple?setPanel('about'):reset()} aria-label="Nikhil Raj, return home"><Asterisk strokeWidth={1.3}/><span>Nikhil Raj</span></Button>
    <nav id="portfolio-navigation" className="nav-pill" aria-label="Portfolio">{(['work','lab','about']as const).map(area=><Button key={area} variant="ghost" className="nav-item" onClick={()=>open(area)}>{area[0].toUpperCase()+area.slice(1)}</Button>)}</nav>
    <div className="audio-controls"><Tool label={sound&&!audioState.unlocked?'Sound starts when you move':sound?'Mute all sound':'Turn sound on'}><Button variant="ghost" size="icon" className="sound-button" onClick={()=>audio.current?.toggle()} aria-label={sound?'Mute all sound':'Turn sound on'} aria-pressed={sound}>{sound?<Volume2/>:<VolumeX/>}<span>{sound?(audioState.unlocked?'Sound on':'Sound ready'):'Sound off'}</span></Button></Tool><Tool label={music?'Turn background music off':'Turn background music on'}><Button variant="ghost" size="icon" className="music-button" onClick={()=>audio.current?.toggleMusic()} aria-label={music?'Turn background music off':'Turn background music on'} aria-pressed={music}><Music2/></Button></Tool></div>
   </header>
   <AnimatePresence>{!simple&&!state.started&&<motion.section className="arrival-copy" initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:8}} transition={{delay:state.ready?.1:0}} aria-label="Welcome"><span className="eyebrow">A SMALL WORLD, OPEN TO EXPLORE</span><TextGenerateEffect words="Make yourself at home." className="arrival-title" duration={reduced?0:.7}/><p>{state.ready?'Just start moving. Curiosity does the rest.':'Gathering a little moon dust…'}</p></motion.section>}</AnimatePresence>
   {!simple&&!state.ready&&!state.error&&<div className="loading-note" role="status"><Orbit className={reduced?'':'loading-orbit'}/><span>Building your view of the moon</span></div>}
   <AnimatePresence>{!simple&&state.visitor&&<motion.aside key={state.visitor} className="visitor-bubble" role="status" aria-live="polite" style={{left:`${state.visitorX}%`,top:`${state.visitorY}%`}} initial={{opacity:0,y:9,scale:.95}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:-7}}><div><Radio size={12}/><span>INCOMING · FRIENDLY VISITOR</span></div><p>{state.visitor}</p></motion.aside>}</AnimatePresence>
   {!simple&&state.started&&state.nearby&&!panel&&<motion.div className="nearby-action" initial={{opacity:0,y:7}} animate={{opacity:1,y:0}}><Button variant="outline" onClick={()=>open(state.nearby)}><kbd>E</kbd>{state.nearby==='work'?'Visit the workshop':state.nearby==='lab'?'Recharge your curiosity':'Meet Nikhil'}<ArrowUpRight size={14}/></Button></motion.div>}
   {simple&&<section className="simple-view"><BlurFade><span className="eyebrow">NIKHIL RAJ / PERSONAL PORTFOLIO</span><h1>A small world.<br/>An open mind.</h1><p>{state.error||'Work, experiments, and a little curiosity. Everything is available here without the 3D world.'}</p><div className="simple-actions">{(['work','lab','about']as const).map(a=><Button key={a} variant="outline" onClick={()=>open(a)}>{a[0].toUpperCase()+a.slice(1)}<ArrowUpRight/></Button>)}</div><Button variant="ghost" onClick={()=>{location.href=location.pathname;}}>Return to the moon <Orbit/></Button></BlurFade></section>}
   <footer className="lunar-footer">
    {!simple&&<div className="movement-hint"><Keyboard size={15}/><span><strong>WASD</strong> / arrows to move</span><span className="hint-divider"/><MousePointer2 size={14}/><span>Drag to orbit</span></div>}
    <div className="footer-right">{!simple&&<span className="world-note"><span className="live-dot"/>A LITTLE MOON, ALL YOURS</span>}<Tool label="Return to home base"><Button variant="ghost" size="icon" aria-label="Return to home base" onClick={reset} disabled={simple||!state.ready}><RotateCcw size={16}/></Button></Tool><Tool label="Controls and settings"><Button variant="ghost" size="icon" aria-label="Controls and settings" onClick={()=>open('controls')}><Settings2 size={17}/></Button></Tool></div>
   </footer>
   {!simple&&state.ready&&<div className="touch-directions" aria-label="Move the robot"><Button variant="outline" size="icon" aria-label="Move forward" className="touch-up" onPointerDown={direction(0,-1)} onPointerUp={stop} onPointerCancel={stop} onLostPointerCapture={stop}><ArrowUp/></Button><Button variant="outline" size="icon" aria-label="Move left" className="touch-left" onPointerDown={direction(-1,0)} onPointerUp={stop} onPointerCancel={stop} onLostPointerCapture={stop}><ArrowLeft/></Button><Button variant="outline" size="icon" aria-label="Move backward" className="touch-down" onPointerDown={direction(0,1)} onPointerUp={stop} onPointerCancel={stop} onLostPointerCapture={stop}><ArrowDown/></Button><Button variant="outline" size="icon" aria-label="Move right" className="touch-right" onPointerDown={direction(1,0)} onPointerUp={stop} onPointerCancel={stop} onLostPointerCapture={stop}><ArrowRight/></Button></div>}
   <Dialog open={!!panel} onOpenChange={v=>{if(!v)setPanel(null);}}><DialogContent className="portfolio-dialog" onOpenAutoFocus={e=>{e.preventDefault();dialogHeading.current?.focus({preventScroll:true});}} onCloseAutoFocus={e=>{e.preventDefault();returnFocus.current?.focus();}}>
    <DialogHeader><span className="eyebrow">{panel==='work'?'01 / THE WORKSHOP':panel==='lab'?'02 / THE CHARGING STATION':panel==='about'?'03 / THE HUMAN BEHIND THE BOT':'A LITTLE FIELD GUIDE'}</span><DialogTitle ref={dialogHeading} tabIndex={-1}>{panel==='work'?'Things worth making.':panel==='lab'?'A place for “what if?”':panel==='about'?'Hello, I’m Nikhil.':'Make yourself at home.'}</DialogTitle><DialogDescription>{panel==='work'?'A growing collection of projects, experiments and ideas.':panel==='lab'?'Take a moment. Try something. Follow your curiosity.':panel==='about'?'Welcome to my little corner of the cosmos.':'The whole moon is yours to explore. No launch sequence required.'}</DialogDescription></DialogHeader>
    {panel==='work'&&<BlurFade><Card className="project-card"><span className="project-label"><Globe2 size={15}/>INTERACTIVE EXPERIENCE</span><h3>Lunar Toybox</h3><p>A tiny moon, a curious bot, and a workshop of ideas. You’re standing in the first project.</p><div className="project-tags"><Badge variant="outline">3D world</Badge><Badge variant="outline">Interaction</Badge><Badge variant="outline">Web</Badge></div><Button variant="outline" onClick={()=>setPanel(null)}>Back to the experience <ArrowUpRight/></Button></Card><p className="content-pending">More projects and case studies are being added here.</p></BlurFade>}
    {panel==='lab'&&<BlurFade><Card className="experiment-card"><Satellite strokeWidth={1.4} size={37}/><h3>We’re not alone out here.</h3><p>Friendly visitors occasionally drift past the moon. Send a little signal and see who stops by.</p><Button variant="outline" disabled={!state.ready||simple||!visitors} onClick={visit}><Radio size={15}/>Send a signal</Button>{!visitors&&<p className="content-pending">Enable visitors in settings to send a signal.</p>}</Card><p className="content-pending">There’s a small surprise on the other side of the moon, too.</p></BlurFade>}
    {panel==='about'&&<BlurFade><div className="about-mark"><Asterisk size={46} strokeWidth={1}/><span>Nikhil Raj</span></div><p className="about-copy">{identity.bio||'A curious mind. A work in progress. This space is for the things I build, try, and care about.'}</p><p className="content-pending">A fuller introduction and contact links are coming next.</p><div className="contact-links">{(['github','linkedin','email']as const).map(key=>{const href=safeLink(key==='email'&&identity.email?`mailto:${identity.email}`:identity[key]);return href?<Button asChild key={key} variant="outline"><a href={href} target="_blank" rel="noreferrer">{key}<ArrowUpRight/></a></Button>:null;})}</div></BlurFade>}
    {panel==='controls'&&<div className="control-content"><div className="control-row"><Move/><div><strong>Find your own path</strong><p>WASD / arrows to move. Shift to boost. On touch, use the direction pad.</p></div></div><div className="control-row"><Orbit/><div><strong>A different perspective</strong><p>Drag to orbit. Scroll / pinch to zoom. R to return home.</p></div></div><div className="control-row"><Sparkles/><div><strong>Follow your curiosity</strong><p>E at a landmark, or use Work, Lab and About anytime.</p></div></div><AudioSettings state={audioState} audio={audio.current}/><Button variant="outline" className="setting-button" onClick={toggleVisitors} aria-pressed={visitors}><Satellite/><span>Passing visitors</span><strong>{visitors?'On':'Off'}</strong></Button><Button variant="ghost" onClick={()=>{setPanel(null);setFlat(true);}}><Accessibility/>Use the simple portfolio <ArrowUpRight/></Button><p className="motion-note">{reduced?'Reduced motion is on. Camera transitions and ambient motion are minimized.':'Motion follows your device’s accessibility preferences.'}</p></div>}
    <div className="dialog-footer"><span>NIKHIL RAJ / LUNAR TOYBOX</span><Button variant="ghost" onClick={()=>setPanel(null)}>Back to {simple?'portfolio':'the moon'}<ArrowRight size={14}/></Button></div>
   </DialogContent></Dialog>
  </main>
 </TooltipProvider></MotionConfig>;
}

function AudioSettings({state,audio}:{state:AudioSnapshot;audio:WorkshopAudio|null}){
 const prefs=state.preferences;
 return <Card className="audio-settings"><div className="audio-settings-heading"><Volume2 size={17}/><strong>A small world · elevenlabs.io</strong></div><p className="audio-description">A motor with a little character. A soundtrack for wandering.</p>{([
  {key:'music',volume:'musicVolume',label:'Background music',icon:Music2},
  {key:'effects',volume:'effectsVolume',label:'Robot & visitors',icon:Satellite},
  {key:'ambience',volume:'ambienceVolume',label:'Space ambience',icon:Orbit},
 ] as const).map(({key,volume,label,icon:Icon})=><div className="audio-channel" key={key}><div className="audio-channel-heading"><span><Icon size={14}/>{label}</span><Button variant="ghost" size="sm" aria-label={`${prefs[key]?'Disable':'Enable'} ${label.toLowerCase()}`} aria-pressed={prefs[key]} onClick={()=>{audio?.setPreferences({[key]:!prefs[key]});audio?.unlock();}}>{prefs[key]?'On':'Off'}</Button></div><div className="audio-level"><Slider aria-label={`${label} volume`} min={0} max={100} step={1} value={[Math.round(prefs[volume]*100)]} onValueChange={([value])=>audio?.setPreferences({[volume]:value/100})}/><output aria-hidden="true">{Math.round(prefs[volume]*100)}%</output></div></div>)}<p className="audio-status" role="status">{state.errors.length?'Some sounds couldn’t load.':state.loading?'Preparing the soundscape…':prefs.muted?'All sound is muted. Use the speaker above to listen.':!state.unlocked?'Sound begins with your first move. Music is optional.':'Your sound preferences are saved on this device.'}</p>{state.errors.length>0&&<Button variant="outline" onClick={()=>audio?.unlock()}>Retry audio</Button>}</Card>;
}
